Adding the places' views and urls.
mehalyna/CarWashing-System pull request #115
Opened 2022-08-07 21:24 UTC by keremidarski

2022-08-08 13:40 UTC, strangerok1507 requested changes

2022-08-08 13:40 UTC, strangerok1507 commented on Carwash/places/views.py
> +def place_name_view(request):
it's not api endpoint. render use for rendering HTML page

2022-08-10 16:17 UTC, VovaD199 approved these changes

2022-08-10 16:28 UTC, closed without merging

2022-08-10 16:29 UTC, keremidarski commented
I closed this PR and I'll try to resolve the problem.