Create DRF views and fix url paths
mehalyna/CarWashing-System pull request #121
Opened 2022-08-08 12:40 UTC by BogdanTopalov

2022-08-08 13:42 UTC, strangerok1507 requested changes
replace two views to one modelviewset

2022-08-08 13:42 UTC, strangerok1507 commented on Carwash/users/urls.py
> +    path('', UsersList.as_view(), name="all users"),
it's good that you learn something else, but for these endpoints, I recommend using modelviewset

2022-08-10 16:39 UTC, VovaD199 approved these changes

2022-08-10 16:41 UTC, VovaD199 approved these changes

2022-08-10 16:43 UTC, VovaD199 approved these changes

2022-08-10 16:43 UTC, VovaD199 approved these changes
Approve to merge

2022-08-10 16:52 UTC, VovaD199 approved these changes

2022-08-10 17:46 UTC, strangerok1507 approved these changes

2022-08-10 17:53 UTC, merged