Places tests
mehalyna/CarWashing-System pull request #167
Opened 2022-08-25 16:59 UTC by keremidarski

2022-08-26 12:17 UTC, strangerok1507 requested changes

2022-08-26 12:17 UTC, strangerok1507 commented on Carwash/places/tests/factories.py
> +
check this file by "black"

2022-08-26 15:28 UTC, keremidarski commented on Carwash/places/tests/factories.py
> +
Checked it - nothing changed.

2022-09-05 14:29 UTC, strangerok1507 approved these changes
really minor changes
+1

2022-09-05 14:29 UTC, strangerok1507 commented on Carwash/places/tests/views/test_places_views.py
> +
no new line

2022-09-05 14:29 UTC, strangerok1507 commented on Carwash/places/tests/factories.py
> +
no new line

2022-09-14 15:39 UTC, merged